import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/navbar/navbar";
import ClientSidebar from "@/components/sidebar/clientSidebar";
import clsx from "clsx";
import ThemeProviderWrapper from "./themeProviderWrapper";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={clsx(geistSans.variable, geistMono.variable, "antialiased")}
      >
        <ThemeProviderWrapper>
          <main className="flex min-h-screen">
            <div className="h-screen min-h-screen sticky top-0">
              <ClientSidebar />
            </div>
            <div className="w-full mx-2">
              <div className="h-[60px] z-10 bg-white dark:bg-gray-900 sticky top-0">
                <Navbar />
              </div>
              <div className="min-h-[calc(100vh-60px-8px)] mt-2">{children}</div>
            </div>
          </main>
        </ThemeProviderWrapper>
      </body>
    </html>
  );
}
/* h-60  w-16 w-64*/
