import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/navbar/navbar";
import ClientSidebar from "@/components/sidebar/clientSidebar";
import clsx from "clsx";
import ThemeProviderWrapper from "./themeProviderWrapper";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={clsx(
          geistSans.variable,
          geistMono.variable,
          "antialiased bg-surface-100 dark:bg-surface-900"
        )}
      >
        <ThemeProviderWrapper>
          <main className="flex min-h-screen bg-surface-100 dark:bg-surface-900">
            <div className="h-screen min-h-screen sticky top-0">
              <ClientSidebar />
            </div>
            <div className=" mx-2 flex-1 flex flex-col w-full">
              <div className="h-[60px] z-50 bg-surface-50 dark:bg-surface-800 backdrop-blur-sm sticky top-0">
                <Navbar />
              </div>
              <div className="flex-1 mt-2 relative">
                {children}
              </div>
            </div>
          </main>
        </ThemeProviderWrapper>
      </body>
    </html>
  );
}
